### PR TITLE
Reduce sync storage size

### LINKED ISSUE #37: BUG: Unable to add more students
**Associated branch**
master

**Describe the bug**
After the Chrome storage quota has been reached, users are unable to add more classes or students.

**To Reproduce**
1. Add lots of classes and students

**Expected behavior**
Teachers are able to add up to 200 students. When they hit the limit, they receive a descriptive error message.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: All

**Additional context**
There isn't a good way to know how many students a teacher can add; it depends on the length of the class and student names.

### PR DESCRIPTION
**Pull request by SeanMcP**
Fixes #37

[Chrome's `sync` storage](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) has a limited number of keys, bytes per key, and bytes overall.

Item|Limit
---|---
`MAX_ITEMS`|512
`QUOTA_BYTES`|102400
`QUOTA_BYTES_PER_ITEM`|8192

This meant that users with a lot of classes and/or a lot of students per class, would hit the limit and be unable to add new students. Big problem!

A contributing factor to this was the data structure for `studentsByClassId`:

```json
"studentsByClassId": {
  "1626294508614": {
      "1628883597952": "Alejandro",
      "1628883607805": "Baruch",
      "1628883617884": "Cassidy",
      "1628883780478": "Dharia",
      "1628883783147": "Edgar"
    }
}
```

To help resolve this issue, I opted for a simple string array instead, which yielded significant savings:

```json
"studentsByClassId": {
  "1626294508614": ["Alejandro", "Baruch", "Cassidy", "Dharia", "Edgar"]
}
```

I also shortened class ids:

```json
"studentsByClassId": {
  "c0": ["Alejandro", "Baruch", "Cassidy", "Dharia", "Edgar"],
  "c1": []
}
```

Finally, I moved `history` to `local` storage, where it should have been all along.

Hopefully these changes will prevent any issues with storage limits.

### CODE REVIEW

**Comment by SeanMcP** [comment]
@bryandagamer That bug I mentioned was fixed in 7c8a673

**Comment by SeanMcP** [comment]
Some scenarios that we'll want to add for this PR:

1. A user has data in an older version of the extension and then updates to this version (you may need to have git running to test this)
2. A user who uploads data from an older version of the extension

Since the data has changed structure, I'll update the examples in `qa/` for testing.
- [x] Rename `valid.json` to `valid-v0.json`
- [x] Add `valid-v1.json`
- [x] Update file references in `test-plan.md`
- [x] Update data properties in `test-plan.md`

Done in 820593464a43987b3728fd0a8261421da0aa2fbf

**Comment by bryandagamer** [comment]
# Test plan

## Setup

### Git

- [x] Go to https://github.com/seanmcp/popsicle-sticks-extension
- [x] Clone the repository
- [x] Check out the branch to be tested
- [ ] Go to chrome://extensions
- [ ] Select "Load unpacked" > Select directory

### Manual

- [ ] Go to https://github.com/seanmcp/popsicle-sticks-extension
- [ ] Select the branch to be tested
- [ ] Select "Code" > "Download ZIP"
- [ ] Unzip on your computer
- [ ] Go to chrome://extensions
- [ ] Select "Load unpacked" > Select directory

## Cases

These are designed to be run in order, so some cases depend on previous ones.

### Add class/student flows

- [ ] Input class name > Select "Add class" > **Navigate automatically to class page**
- [ ] Select class > **See class name in header**
- [ ] Select class > **DO NOT see "Copy another class?" link**
- [ ] Select class > Input student name > Select "Add student" > **Student is rendered in list**
- [ ] Select class > Input repeated student name > Select "Add student" > **Alert about duplicate student names**
- [ ] Select class > Select "Add multiple students" > Input students with new lines > Select "Add all" > **1) Navigate back to class view; 2) Students are rendered in list**
- [ ] Select class > Select "Add multiple students" > Input students separated by commas > Select "Names separated by commas" > Select "Add all" > **1) Navigate back to class view; 2) Students are rendered in list**
- [ ] Select class > Select "Remove student" > **Student is removed from list**
- [ ] Input class name > Select "Add class" > **See "Copy another class?" link on class page**
- [ ] Select class B > Select "Copy another class?" > **Navigate to copy page**
- [ ] Select class B > Select "Copy another class?" > Select class A > Select "Copy" > **1) Navigate back to class view; 2) Students from class A are copied to class B**
- [ ] Select class B > Input student name > **Student IS in class B BUT NOT in class A**
- [ ] Select class B > Select "Delete this class" > **1) Navigate back to home view; 2) Class B is removed from list**

### Random picker

- [ ] Select class > Select "Random Picker" > **A student from this class is displayed**
  - [ ] Select "Next" > **See a different student from the class**
  - [ ] Select "Previous" > **See the first student**
  - [ ] Select "Next" until through class > **1) List continues infinitely; 2) Order is shuffled**
    - **Note**: A name may repeat if it was the last in one set, and then the first in a second shuffled set. This is unlikely with larger classes but more probable with smaller test classes.
  - [ ] Select "Back" > **Navigate to class page**

### Theme

- [ ] Select "Settings" > Select "Dark" theme > **1) Theme changes on selection; 2) Theme is correct for all pages:**
  - [ ] **Backup**
  - [ ] **Home**
  - [ ] **Class**
  - [ ] **Bulk**
  - [ ] **Copy**
  - [ ] **Random**

### Data/backup

- [ ] Select "Settings" > Select "Download or upload your class and student data" > **1) See option to download data; 2) See option to upload data**
- [ ] Select "Settings" > Select "Download or upload your class and student data" > Select "Download data" > **Triggers JSON download**
- [ ] Open downloaded file > **Contains keys: `classes`, `secret`, `studentsByClassId`, `theme`**
- [ ] Open downloaded data file > **1) Is valid JSON; 2) Has all of the following:**
  - [ ] **`classes` property matches expected values**
  - [ ] **`studentsByClassId` property matches expected values**
  - [ ] **`secret` property is "Luke 8:17"**
  - [ ] **`theme` data is correct**
  - [ ] **Missing class B in `classes` and `studentsByClassId`**
- [ ] Select "Settings" > Select "Download or upload your class and student data" > Select "Choose file" > Select `qa/invalid.json` > Select "Upload" > **1) See error message "That data wasn't formatted correctly"; 2) No data changes are applied**
- [ ] Select "Settings" > Select "Download or upload your class and student data" > Select "Choose file" > Select `qa/empty.json` > Select "Upload" > **1) See error message "That file did not originate from this extension"; 2) No data changes are applied**
- [ ] Select "Settings" > Select "Download or upload your class and student data" > Select "Choose file" > Select `qa/valid.json` > Select "Upload" > **1) Navigate back to home view; 2) Data for three classes and their students applied correctly**

### History

All of these cases are from a cold start

- [ ] Open extension > Navigate to page > Close extension > Open extension > **See last visited page**
  - [ ] **Backup**
  - [ ] **Bulk**
  - [ ] **Class**
  - [ ] **Copy**
  - [ ] **Random**
- [ ] Open extension > Select class > Select "Random Picker" > Close extension > Open extension > **See same student**
- [ ] Open extension > Navigate to page > Close extension > Wait 5 minutes > Open extension > **See home page**

### Pop out

- [ ] **See "Pop out in new window" button**
- [ ] Select "Pop out in new window" > **See pop out of current page**
- [ ] Select "Pop out in new window" > Select class > Close pop out > Open extension > **See last visited page from pop out**
- [ ] Select class > Select "Random Picker" > **See "Pop out in new window" button**
- [ ] Select class > Select "Random Picker" > Select "Pop out in new window" > **See pop out of current page and state**

**Comment by SeanMcP** [comment]
@bryandagamer I figured out the specific setup required for that first scenario, "A user has data in an older version of the extension and then updates to this version". We can talk through the reasoning for this in more detail later, but I'll list out the steps here:

1. Remove all local versions of the extension
2. Checkout the `master` branch
3. Select "Load unpacked" > select directory
4. Open extension
5. Add some test class/student data
6. Checkout the feature branch
7. In Chrome, select extension's "refresh" button
8. Open extension
9. Confirm that class/student data is preserved
10. Download data > confirm that `classes`/`studentsByClassId` matches v1 format

If you get a chance before our next meeting, can you try to run through these steps to confirm that the issue we saw yesterday isn't something to do with our environments (mac vs windows)?

**Pull request merged**
